import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce', timezoneId: 'America/Montevideo' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.clock.setFixedTime(new Date('2026-10-07T15:00:00Z'));
await page.goto('http://127.0.0.1:5173');
await page.getByRole('heading', { name: /Salí de la rutina/ }).waitFor();
await page.evaluate(() => document.fonts.ready);
await mkdir('docs/screenshots/theme', { recursive: true });
let captures = 0;
async function capture(name, fullPage = false) {
  await page.screenshot({ path: `docs/screenshots/theme/${name}.png`, animations: 'disabled', fullPage });
  captures++;
}
await page.getByRole('button', { name: 'Activar modo claro' }).click();
await page.waitForSelector('.theme-toggle .lucide-moon');
await capture('home-light');
await page.getByRole('button', { name: 'Encontrá tu experiencia' }).click();
await page.waitForSelector('.header-floating');
await capture('catalog-light');
await page.getByRole('button', { name: 'Notificaciones', exact: true }).click();
await capture('notifications-light');
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Ver Supernova Sessions', exact: true }).click();
await capture('registration-light');
await page.getByRole('button', { name: 'Confirmar mi lugar', exact: true }).click();
await page.getByRole('alert').waitFor();
await capture('toast-light');
await page.getByRole('checkbox', { name: 'Acepto los términos y condiciones del evento.' }).check();
await page.getByRole('button', { name: 'Confirmar mi lugar', exact: true }).click();
await page.getByRole('heading', { name: 'Ya sos parte.' }).waitFor();
await capture('pass-light');
await page.setViewportSize({ width: 390, height: 667 });
await capture('pass-light-mobile');
await page.setViewportSize({ width: 1440, height: 900 });
await page.getByRole('button', { name: 'Cerrar inscripción' }).click();
await page.getByRole('button', { name: 'Administrar', exact: true }).click();
await page.getByRole('button', { name: 'Crear experiencia', exact: true }).waitFor();
await capture('admin-light');
await page.getByRole('button', { name: 'Crear experiencia', exact: true }).click();
await page.getByLabel('Nombre del evento').waitFor();
await capture('studio-light');
await page.getByRole('combobox', { name: 'Categoría', exact: true }).click();
await page.getByRole('listbox', { name: 'Categoría', exact: true }).waitFor();
await capture('select-light');
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Abrir calendario de fecha y hora de inicio' }).click();
await page.getByRole('dialog', { name: 'Calendario de fecha y hora de inicio' }).waitFor();
await capture('calendar-light');
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Volver a eventos' }).click();
await page.getByRole('button', { name: 'Abrir perfil de Alex García' }).click();
await capture('profile-menu-light');
await page.getByRole('button', { name: 'Ver mi perfil', exact: true }).click();
await page.getByRole('heading', { name: 'Mi perfil', exact: true }).waitFor();
await capture('profile-light');
await page.getByRole('button', { name: 'Explorar', exact: true }).click();
await page.setViewportSize({ width: 390, height: 844 });
await page.getByRole('heading', { name: /Salí de la rutina/ }).waitFor();
await page.waitForFunction(() => getComputedStyle(document.querySelector('.hero h1')).opacity === '1');
await capture('home-light-mobile');
await page.setViewportSize({ width: 1440, height: 900 });
await page.getByRole('button', { name: 'Activar modo oscuro' }).click();
await page.evaluate(() => scrollTo(0, 0));
await capture('home-dark');
console.log(JSON.stringify({ captures, pageErrors: errors }));
await browser.close();
