import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'reduce', timezoneId: 'America/Montevideo' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.clock.setFixedTime(new Date('2026-10-07T15:00:00Z'));
await page.goto('http://127.0.0.1:5173');
await page.waitForSelector('.event-card');
await page.evaluate(() => document.fonts.ready);
await page.waitForFunction(() => getComputedStyle(document.querySelector('.hero h1')).opacity === '1');
await mkdir('docs/screenshots', { recursive: true });
await page.screenshot({ path: 'docs/screenshots/home-desktop.png', animations: 'disabled' });
await page.getByRole('button', { name: 'Encontrá tu experiencia' }).click();
await page.waitForSelector('.header-floating');
await page.screenshot({ path: 'docs/screenshots/catalog-desktop.png', animations: 'disabled' });
await page.getByRole('button', { name: 'Ver Supernova Sessions', exact: true }).click();
await page.screenshot({ path: 'docs/screenshots/registration-desktop.png', animations: 'disabled' });
await page.getByRole('button', { name: 'Confirmar mi lugar', exact: true }).click();
await page.getByRole('alert').waitFor();
await page.screenshot({ path: 'docs/screenshots/registration-toast.png', animations: 'disabled' });
await page.getByRole('button', { name: 'Cerrar inscripción' }).click();
await page.getByRole('button', { name: 'Administrar', exact: true }).click();
await page.getByRole('button', { name: 'Crear experiencia', exact: true }).waitFor();
await page.waitForFunction(() => getComputedStyle(document.querySelector('.admin-panel')).opacity === '1');
await page.screenshot({ path: 'docs/screenshots/admin-desktop.png', animations: 'disabled' });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'docs/screenshots/admin-mobile.png', animations: 'disabled' });
await page.setViewportSize({ width: 1440, height: 1000 });
await page.getByRole('button', { name: /Más filtros/ }).click();
await page.getByRole('combobox', { name: 'Estado', exact: true }).click();
await page.getByRole('option', { name: 'Publicados', exact: true }).click();
await page.getByRole('button', { name: 'Buscar', exact: true }).click();
await page.screenshot({ path: 'docs/screenshots/admin-applied-filters.png', animations: 'disabled' });
await page.getByRole('button', { name: /Ver filtros aplicados: Estado/ }).click();
await page.getByRole('dialog', { name: 'Filtros aplicados', exact: true }).waitFor();
await page.screenshot({ path: 'docs/screenshots/admin-filter-dialog.png', animations: 'disabled' });
await page.getByRole('button', { name: 'Cerrar filtros', exact: true }).click();
await page.getByRole('button', { name: 'Reiniciar filtros', exact: true }).click();
await page.getByRole('button', { name: 'Crear experiencia', exact: true }).click();
await page.getByLabel('Nombre del evento').waitFor();
await page.screenshot({ path: 'docs/screenshots/wizard-desktop.png', animations: 'disabled' });
await page.getByRole('combobox', { name: 'Categoría', exact: true }).click();
await page.getByRole('listbox', { name: 'Categoría', exact: true }).waitFor();
await page.screenshot({ path: 'docs/screenshots/wizard-select.png', animations: 'disabled' });
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Abrir calendario de fecha y hora de inicio' }).click();
await page.getByRole('dialog', { name: 'Calendario de fecha y hora de inicio' }).waitFor();
await page.screenshot({ path: 'docs/screenshots/wizard-calendar.png', animations: 'disabled' });
await page.keyboard.press('Escape');
await page.getByRole('switch', { name: 'Activar términos y condiciones' }).check();
await page.getByLabel('Condiciones de participación').fill('Aceptá estas condiciones para participar de la experiencia.');
await page.getByRole('switch', { name: 'Activar términos y condiciones' }).scrollIntoViewIfNeeded();
await page.screenshot({ path: 'docs/screenshots/wizard-terms.png', animations: 'disabled' });
await page.getByRole('button', { name: 'Volver a eventos' }).click();
await page.getByRole('button', { name: 'Explorar', exact: true }).click();
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForSelector('.event-card');
await page.screenshot({ path: 'docs/screenshots/home-mobile.png', animations: 'disabled' });
const overflow = [];
for (const width of [320, 390, 768, 1024, 1440, 1920, 2560]) {
  await page.setViewportSize({ width, height: 1000 });
  overflow.push({ width, overflow: await page.evaluate(() => document.documentElement.scrollWidth > innerWidth) });
}
await page.setViewportSize({ width: 1920, height: 818 });
await page.screenshot({ path: 'docs/screenshots/home-wide.png', animations: 'disabled' });
await page.setViewportSize({ width: 1440, height: 1000 });
await page.getByRole('button', { name: 'Guardar Supernova Sessions', exact: true }).click();
await page.getByRole('button', { name: /^Favoritos/ }).click();
await page.getByRole('heading', { name: 'Esos planes que te guardaste.' }).waitFor();
await page.waitForFunction(() => getComputedStyle(document.querySelector('.favorites-page').parentElement).opacity === '1');
await page.screenshot({ path: 'docs/screenshots/favorites-desktop.png', animations: 'disabled' });
await page.getByRole('button', { name: 'Explorar', exact: true }).click();
await page.getByRole('button', { name: 'Ver Supernova Sessions', exact: true }).click();
await page.getByRole('checkbox', { name: 'Acepto los términos y condiciones del evento.' }).check();
await page.getByRole('button', { name: 'Confirmar mi lugar', exact: true }).click();
await page.getByRole('heading', { name: 'Ya sos parte.' }).waitFor();
await page.screenshot({ path: 'docs/screenshots/registration-ticket.png', animations: 'disabled' });
await page.setViewportSize({ width: 390, height: 667 });
await page.screenshot({ path: 'docs/screenshots/registration-ticket-mobile.png', animations: 'disabled' });
await page.setViewportSize({ width: 1440, height: 1000 });
await page.getByRole('button', { name: 'Cerrar inscripción' }).click();
await page.getByRole('button', { name: 'Abrir perfil de Alex García' }).click();
await page.screenshot({ path: 'docs/screenshots/profile-desktop.png', animations: 'disabled' });
await page.getByRole('button', { name: 'Ver mi perfil', exact: true }).click();
await page.getByRole('heading', { name: 'Mi perfil', exact: true }).waitFor();
await page.waitForFunction(() => getComputedStyle(document.querySelector('.profile-page').parentElement).opacity === '1');
await page.screenshot({ path: 'docs/screenshots/profile-page.png', animations: 'disabled' });
await page.getByRole('button', { name: 'Notificaciones', exact: true }).click();
await page.screenshot({ path: 'docs/screenshots/notifications-desktop.png', animations: 'disabled' });
await page.keyboard.press('Escape');
const introPage = await context.newPage();
introPage.on('pageerror', error => errors.push(error.message));
await introPage.emulateMedia({ reducedMotion: 'no-preference' });
await introPage.goto('http://127.0.0.1:5173');
await introPage.getByRole('dialog', { name: 'Bienvenido a Supernova Eventos' }).waitFor();
await introPage.waitForTimeout(2400);
await introPage.screenshot({ path: 'docs/screenshots/intro-desktop.png' });
await introPage.keyboard.press('Escape');
console.log(JSON.stringify({ screenshots: 21, pageErrors: errors, responsive: overflow }));
await browser.close();
